### ISSUE TITLE
Comparison Write-up

### ISSUE THREAD

**Issue by HeidiJoe** [stinb/UnderstandForVSCode#13]
Robby, I would like to have a comparison write-up for VSCode against at least one other option. You verbally compared it to Microsoft's C/C++ plugin (I think that's the one it was) and I would like to have that as a written out comparison so we can use it on marketing materials, maybe the marketplace, front web page, support site, etc. If there are other VSCode tools or plugins to compare it to, that would be great as well to add more. 

On the scitools.com home page we have a section about the plugin and I want to make sure that the paragraph is highlighting features that can't/aren't being done in VSCode that are more unique to Understand. If you have any suggestions for this that would be great (and this may easily come from the comparison request above).

**Comment by RobbyCBennett** [comment]
I made an edit. I guess the user doesn't have to analyze all files on open for Microsoft's extension for all things. It looks like you just have to do it for the errors/warnings. The references and hover info seem to be saved.

**Comment by RobbyCBennett** [comment]
I made another edit. I included a benchmark for analysis times.

**Comment by RobbyCBennett** [comment]
There are other extensions that I could consider as well. The Microsoft one is the most obvious candidate with 27.3 million installs. 
- [C/C++ Advanced Lint with 515K installs](https://marketplace.visualstudio.com/items?itemName=jbenden.c-cpp-flylint)
- [Parasoft C/C++test with 44K installs](https://marketplace.visualstudio.com/items?itemName=parasoft.vscode-cpptest)

**Comment by RobbyCBennett** [comment]
I found some more C++ static analysis extensions. I have updated [my comment](https://github.com/stinb/UnderstandForVSCode/issues/13#issuecomment-2038217516).

**Comment by RobbyCBennett** [comment]
I'm pretty that this is done. I'll close it.
