### ISSUE TITLE
Include licensing with link to pricing page on the vs code marketplace

### ISSUE THREAD

**Issue by KylorKersavage** [stinb/UnderstandForVSCode#17]
talk to Heidi

**Comment by KylorKersavage** [comment]
maybe like this
![image](https://github.com/stinb/UnderstandForVSCode/assets/105667297/dcad1cda-3761-4f91-86d6-4c91a5ed0f5b)

**Comment by RobbyCBennett** [comment]
Add the following to the top of the readme:
- [ ] Licensing (no prices, just the fact that you need a license)
- [ ] Comparisons (Microsoft C/C++ and [2 others](https://github.com/stinb/UnderstandForVSCode/issues/13#issuecomment-2038217516)) at the top

**Comment by RobbyCBennett** [comment]
Fixed in b137e6849dc4a90695354e8d0781d59f0020a588
