### ISSUE TITLE
Errors are only cleared if background checks are enabled

### ISSUE THREAD

**Issue by RobbyCBennett** [stinb/UnderstandForVSCode#19]
Replicate:
1. Disable background checks
2. Find an error-free file
3. Add a syntax error
4. Analyze
5. Fix the syntax error
6. Analyze

![image](https://github.com/stinb/UnderstandForVSCode/assets/22121365/580d651a-537b-4e23-ad81-cc646d92f0fc)

I always use background checks, so I haven't noticed this until now.

**Comment by RobbyCBennett** [comment]
I noticed that old UND_ERROR violations are removed with analyze changed files (`Analyzer::parseChanged`), but not removed with analyze specific files (`Analyzer::parseFiles`). A simple fix would be to call `parseChanged` instead. However, that would slow down the interface a lot. Here's  an example of times with a big project:
- Analyze changed files: 6.24 sec
- Analyze specific list of files: 4.22 sec

**Comment by RobbyCBennett** [comment]
@hackhaslam do you know why I still see old errors with the `IssueManager` when background CodeChecks are disabled? I only see it in userver and not Understand, so I guess I'm doing something wrong.

**Comment by hackhaslam** [comment]
It's probably fixed by facd01e0cd211dcfa51b9f83ac13b65eb7a26932 that I just checked in. Those calls are required during the parse to be able to create and clear error/warning issues.

**Comment by RobbyCBennett** [comment]
Yes, that fixed it. Thank you. I didn't know that I had to do that.
