### ISSUE TITLE
Polish for release

### ISSUE THREAD

**Issue by RobbyCBennett** [stinb/UnderstandForVSCode#2]
- ~Automatically analyze all files or prompt on project config changed~: not going to fix now (not even available in Understand on project open)
- [x] Make an account support@scitools.com with identifier `scitools`
- [x] Remove all right-click menu items that might not work
- [x] Add all features to documentation
- [x] Fix code action lightbulb on wrong line (actually, the lightbulb is supposed to be above, but the happens with left-clicking anywhere but the left of the token because the client is inconsistent with sending back diagnostics)
- [x] Make sure that references and others have commands
- [x] Use `setContext` to make a new context called `understandFile` to narrow down available commands
- [x] Remove duplicate violations (https://github.com/stinb/sti/issues/3146)
- [x] Wait for the verified blue checkmark on the [marketplace](https://marketplace.visualstudio.com/publishers/scitools) (should be at latest Tuesday, Feb 6)
- [x] Automatically analyze all files or prompt on database wrong version
- [x] Add another release (https://github.com/stinb/UnderstandForVSCode/releases/tag/v0.9.2-beta)
- [x] Have Kate test it
- [x] https://github.com/stinb/UnderstandForVSCode/issues/4
- [x] https://github.com/stinb/UnderstandForVSCode/issues/7
- [x] Make this repo public, fix images in README, remove `baseImagesUrl` from Makefile and wiki
- [ ] Have Heidi assign others to test it

**Comment by groke** [comment]
@RobbyCBennett I made the repo public to help with some testing issues.

**Comment by RobbyCBennett** [comment]
Okay. Since you did that, I just fixed the README so that the images are visible in the editor. That's only possible when the repo is public. I released it as 0.9.4, which is the latest beta release right now.

**Comment by RobbyCBennett** [comment]
Now it's fixed again, for real, in case you downloaded it in the last 6 minutes.

**Comment by RobbyCBennett** [comment]
I will release to the VS Code extension marketplace once we push our next release of Understand.

**Comment by RobbyCBennett** [comment]
Published
