### ISSUE TITLE
Add support for ignores.json

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/UnderstandForVSCode#28]
## Problem(s) this feature will solve
Understand CodeCheck supports baseline violations, but the VSCode plugin does not. I've marked all the violations as baseline, and I noticed that an "ignores.json" file was added to the Understand project.

![image](https://github.com/user-attachments/assets/6fa843b4-dcf7-4f3f-bcf8-fc84798fdf29)

However, as we've previously discussed, it seems that the VSCode extension doesn't consider this file.

## Describe the solution you'd like
Add support for ignores.json

**Comment by groke** [comment]
Baselining should be supported with 7.0, but not the legacy ignores.json
